name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          cache-dependency-glob: pyproject.toml
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
